### ISSUE TITLE
Step 9 generated a different answer

### ISSUE THREAD

**Issue by sfgeekgit** [Russ741/karpathy-nn-z2h#6]
This is awesome! Thanks for making.
I got all the way to the end, passed all the tests for steps 1-8 but then in step 9 my code generated a different word.
At first, my code generated the word "ajain"
Generated word was ajain, expected machina

Figured maybe this was because back in step 2, I did not generate stoi in "alphabetical order" so I went back and changed that to match .=0 a=1, b=2 etc
re-ran all cells and got a different word "drlen"
Generated word was drlen, expected machina

I don't know why they don't match, happy to try to figure it out tomorrow.
This has been a great learning experience, thanks again!

**Comment by Russ741** [comment]
Fixed (well, worked around, anyways) by 815d549. "drlen" only appears to show up when using both Colab and pytorch 2. Your code was fine. Sorry for the inconvenience!
